import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Pavithra",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
    },
    {
      name: "Jaya",
      email: "Jaya@example.com",
      password: bcrypt.hashSync("1234", 8),
    },
  ],
  products: [
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality Product",
    },
    {
      name: "adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Nike",
      rating: 0.5,
      numReviews: 7,
      description: "Good quality Product",
    },
    {
      name: "Locaoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 110,
      countInStock: 10,
      brand: "Locoste",
      rating: 1.5,
      numReviews: 20,
      description: "High quality Product",
    },
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 190,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 25,
      description: "High quality Product",
    },
    {
      name: "Nike Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 200,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 15,
      description: "Good quality Product",
    },
    {
      name: "adidas Slim Pant",
      category: "Pants",
      image: "/images/p46.jpg",
      price: 180,
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 20,
      description: "High quality Product",
    },
  ],
};
export default data;
